name: aerodynamics-simulator
region: fra
services:
- name: api
  github:
    repo: Dreamvention/aerodynamics-simulator
    branch: main
    deploy_on_push: true
  build_command: "cd api && bun install && bun run build"
  run_command: "cd api && bun run start:prod"
  instance_size_slug: apps-s-1vcpu-1gb-fixed
  http_port: 3000

- name: app
  github:
    repo: Dreamvention/aerodynamics-simulator
    branch: main
    deploy_on_push: true
  build_command: "cd app && bun install && bun run build"
  run_command: "cd app && bun run .output/server/index.mjs"
  instance_size_slug: apps-s-1vcpu-1gb-fixed
  http_port: 3000

ingress:
  rules:
  - path:
      prefix: /api
    component:
      name: api
  - path:
      prefix: /
    component:
      name: app
